### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by gerzitom** [markatk/intellij-logitech-craft#1]
How can I install it into intellij and assign actions?
Thank you

**Comment by markatk** [comment]
I am sorry, this is just a placeholder repository. I don't have time to continue the development at the moment.

**Comment by gerzitom** [comment]
Ou, okey, I see
and may I ask, what have you done so far? I Is it working somehow? Because I might be able to help, I wish, there was some better usage of my craft keyboard for jetbrains tools.

**Comment by markatk** [comment]
I have tested the keyboard SDK with some dummy project, but I don't have much working in this project. Sorry to disappoint you
